# Setup containers for base conda environment
# Joseph Burling <joseph@datajoint.com>
# --------------------------------------------------------------------------------------
# Basic usage:
#   docker-compose up --detach
#   docker-compose down

version: "2.4"
services:
  python:
    volumes:
      - ./share:/srv/conda
    environment:
      USER_NAME: user
      USER_UID: 1000
    image: iamamutt/conda_base:latest # conda_base_dev:v0.0.0
    init: true
