name: CI to Docker Hub

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  conda_base_debian:
    runs-on: self-hosted
    steps:
      - name: Get current date
        id: timestamp
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:buildx-stable-1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            IMAGE_CREATED=${{ steps.timestamp.outputs.date }}
            IMAGE_VERSION=${{ github.ref_name }}
          context: ./build/debian
          file: ./build/debian/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/conda_base:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/conda_base:${{ steps.previoustag.outputs.tag }}
          target: conda_base_debian

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
