name: Docker Conda Base Image CI

on:
  push:
    branches: [main]
    #   - "!*"
    # tags:
    #   - "v*"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Github Tag with semantic versioning
        id: semvertag
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          create_annotated_tag: true


      - name: Assign environment variables
        run: |
          echo "image_build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          no-cache: true
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          context: ./build/debian
          file: ./build/debian/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          build-args: |
            IMAGE_CREATED=${{ env.image_build_date }}
            IMAGE_VERSION=${{ steps.semvertag.outputs.new_tag }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/conda_base:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/conda_base:${{ steps.semvertag.outputs.new_tag }}
            ghcr.io/${{ github.repository_owner }}/conda_base:latest
            ghcr.io/${{ github.repository_owner }}/conda_base:${{ steps.semvertag.outputs.new_tag }}
          target: conda_base_debian

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
